name: My First Github Action
on: [push, pull_request]
jobs:
  build_app:
    runs-on: ubuntu-latest
    outputs:
      text: $${{ steps.finished.outputs.text }}
    env: 
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID}}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID}}
      VERCEL_TOKEN: ${{ secrets.TOKEN}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.17.0'
      - run: node -v
      - name: 'Install Dependencies'
        run: yarn
      - name: 'Build'
        run: yarn build
      - name: 'Deploy'
        run: yarn deploy
      - name: 'Setup Finish'
        id: finshed
        run: echo "::set-output-name=text::hello-world-from-build-job"
  test-app:
    needs: build-app # Required for dependent jobs
    runs-on: ubuntu-latest
    env:
      - MY_JOB_OUTPUT: ${{needs.build_app.outputs.text }}
    steps:
      - run: echo 
# myapp:
#   service: |
#     shit
#     this is a multiline string
#   test: shit-2
#   arrayTest:
#     - elem1: 'yo'
#       elem1.1: 'yoy'
#     - elem2: 'yoyo'