name: My First Github Action
on: [push, pull_request]
jobs:
  build-app:
    runs-on: ubuntu-latest
    env: 
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID}}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID}}
      VERCEL_TOKEN: ${{ secrets.TOKEN}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.17.0'
      - run: node -v
      - name: 'Install Dependencies'
        run: yarn
      - name: 'Build'
        run: yarn build
      - name: 'Show Tree'
        run: tree
      - name: 'Deploy'
        run: yarn deploy
  test-app:
    needs: build-app # Required for dependent jobs
    runs-on: ubuntu-latest
    steps:
      - run: yarn test
# myapp:
#   service: |
#     shit
#     this is a multiline string
#   test: shit-2
#   arrayTest:
#     - elem1: 'yo'
#       elem1.1: 'yoy'
#     - elem2: 'yoyo'