name: My First Github Action
on: [push, pull_request]
jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.17.0'
      - run: node -v
      - name: 'Install Dependencies'
        run: yarn
      - name: 'Build'
        run: yarn build
      - name: 'Show Tree'
        run: tree
      - name: 'Deploy'
        env: 
          VERCEL_ORG_ID: 'OVDYwkb4OtXxevhyCgqraqch'
          VERCEL_PROJECT_ID: 'prj_ddKlsqcY4f1Wa1Lt0kEIedpNC8F2'
        run: yarn deploy
# myapp:
#   service: |
#     shit
#     this is a multiline string
#   test: shit-2
#   arrayTest:
#     - elem1: 'yo'
#       elem1.1: 'yoy'
#     - elem2: 'yoyo'