name: My First Github Action
on: [push, pull_request]
jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.17.0'
      - run: node -v
      - run: npm install
      - run: npm build
# myapp:
#   service: |
#     shit
#     this is a multiline string
#   test: shit-2
#   arrayTest:
#     - elem1: 'yo'
#       elem1.1: 'yoy'
#     - elem2: 'yoyo'