name: My First Github Action
on: [push, pull_request]
jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: tree
# myapp:
#   service: |
#     shit
#     this is a multiline string
#   test: shit-2
#   arrayTest:
#     - elem1: 'yo'
#       elem1.1: 'yoy'
#     - elem2: 'yoyo'